from flask import Flask, jsonify, request, render_template_string
import time

app = Flask(__name__)

START_TIME = None
API_RUNNING = False
SELECTED_STATUS = 200


@app.route("/")
def index():
    return render_template_string("""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>API Control Panel</title>

<style>
body {
    font-family: "Segoe UI", sans-serif;
    background: #fff7f0;
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100vh;
}
.card {
    background: white;
    padding: 25px 40px;
    border-radius: 16px;
    box-shadow: 0 3px 10px rgba(0,0,0,0.15);
    text-align: center;
    width: 420px;
}
button {
    background: #ff7b00;
    border: none;
    color: white;
    padding: 10px 20px;
    margin: 10px;
    border-radius: 10px;
    cursor: pointer;
    font-size: 16px;
}
.status { margin-top: 12px; font-size: 18px; font-weight: bold; }
input {
    width: 100%;
}
</style>
</head>

<body>
<div class="card">

    <h2>API Control Panel</h2>

    <button id="toggleBtn">Loading...</button>
    <br>

    <label>Status Code:</label><br>
    <select id="statusCode">
        <option value="200">200 OK</option>
        <option value="400">400 Bad Request</option>
        <option value="404">404 Not Found</option>
        <option value="500">500 Server Error</option>
    </select>

    <div class="status" id="apiStatus"></div>
    <div id="uptime"></div>

    <hr style="margin:18px 0">

    <label><b>API Endpoint</b></label>

    <div style="display:flex;gap:8px;margin-top:8px;">
        <input id="apiUrl" readonly
               style="flex:1;padding:8px;border-radius:8px;border:1px solid #ccc;font-size:14px;">

        <button onclick="copyUrl()">Copy</button>
    </div>

    <div id="copyMsg" style="font-size:14px;color:green;margin-top:6px;"></div>

</div>

<script>
const toggleBtn = document.getElementById("toggleBtn");
const apiStatus = document.getElementById("apiStatus");
const statusCode = document.getElementById("statusCode");
const uptime = document.getElementById("uptime");

async function refreshState(){
    const res = await fetch("/state");
    const data = await res.json();

    // auto build correct API URL
    document.getElementById("apiUrl").value =
        window.location.origin + "/api";

    if(data.running){
        toggleBtn.textContent = "Stop API";
        apiStatus.textContent = "API is Running";
        apiStatus.style.color = "green";
        uptime.textContent = "Uptime: " + data.uptime + " sec";
    } else {
        toggleBtn.textContent = "Start API";
        apiStatus.textContent = "API is Stopped";
        apiStatus.style.color = "red";
        uptime.textContent = "";
    }

    statusCode.value = data.status;
}

toggleBtn.onclick = async ()=>{
    await fetch("/toggle",{method:"POST"});
    refreshState();
};

statusCode.onchange = async ()=>{
    await fetch("/set_status",{
        method:"POST",
        headers:{"Content-Type":"application/json"},
        body:JSON.stringify({status:statusCode.value})
    });
};

function copyUrl(){
    const urlBox = document.getElementById("apiUrl");
    urlBox.select();
    urlBox.setSelectionRange(0,99999);
    navigator.clipboard.writeText(urlBox.value);

    const msg = document.getElementById("copyMsg");
    msg.textContent = "Copied to clipboard!";
    setTimeout(()=>msg.textContent="",1500);
}

setInterval(refreshState,1000);
refreshState();
</script>

</body>
</html>
""")


@app.route("/toggle", methods=["POST"])
def toggle_api():
    global API_RUNNING, START_TIME
    API_RUNNING = not API_RUNNING
    if API_RUNNING:
        START_TIME = time.time()
    return jsonify({"running": API_RUNNING})


@app.route("/set_status", methods=["POST"])
def set_status():
    global SELECTED_STATUS
    data = request.get_json(silent=True) or {}
    SELECTED_STATUS = int(data.get("status", 200))
    return jsonify({"status": SELECTED_STATUS})


@app.route("/state")
def state():
    uptime = int(time.time() - START_TIME) if API_RUNNING and START_TIME else 0
    return jsonify({
        "running": API_RUNNING,
        "status": SELECTED_STATUS,
        "uptime": uptime
    })


@app.route("/api")
def fake_api():
    if not API_RUNNING:
        return jsonify({"error": "API is stopped"}), 503

    return jsonify({
        "message": "Response generated by controlled API",
        "status": SELECTED_STATUS,
        "uptime_seconds": int(time.time() - START_TIME)
    }), SELECTED_STATUS


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=7000, debug=True)